### ISSUE TITLE
Basic set of checks

### ISSUE THREAD

**Issue by portertech** [sensu-community/monitoring-checks#3]
Find or write plugins and create Bonsai Assets and a check definition for the following resources and services:

- [ ] Disk usage
- [ ] Memory / Swap
- [ ] CPU
- [ ] Network utilization
- [ ] HTTP 80 /healthz
- [ ] NTP
- [ ] Load average
- [ ] Prometheus /metrics

Example Asset resource name: "prometheus-collector:1.0.1"

**Comment by webframp** [comment]
Does this mean example configuration using some check like those provided by this project: https://github.com/sensu/monitoring-plugins ?

**Comment by calebhailey** [comment]
This happened! 

https://github.com/sensu-community/monitoring-checks/tree/master/system/linux/disk 

https://github.com/sensu-community/monitoring-checks/tree/master/system/windows/disk

https://github.com/sensu-community/monitoring-checks/tree/master/system/linux/memory

https://github.com/sensu-community/monitoring-checks/tree/master/system/linux/cpu

https://github.com/sensu-community/monitoring-checks/tree/master/system/linux/network

https://github.com/sensu-community/monitoring-checks/tree/master/http

https://github.com/sensu-community/monitoring-checks/tree/master/ntp

https://github.com/sensu-community/monitoring-checks/tree/master/system/linux/load

We haven't added a generic Prom /metrics collector yet, but we have a few good examples in the new repo:

https://github.com/sensu/catalog/blob/main/monitors/node_exporter/node_exporter.yaml 

https://github.com/sensu/catalog/blob/main/monitors/kubernetes/kubelet.yaml

💥
